project:
  output-dir: ./outputs/
  title: "eLife Template"
  type: default

bibliography: references.bib
appendix: appendix.Rmd

format: 
  pdf: 
    template: elife-template.tex
    pdf-engine: pdflatex

  latex: 
    template: elife-template.tex
